spring.application.name=petshop-care-api
server.port=8282

# MySQL
spring.datasource.url=jdbc:mysql://db:3306/petshopcare?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Manaus
spring.datasource.username=petshop
spring.datasource.password=petshop123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=petshopcare2025segredosupersecretochavemuitorandomicanaomudar
jwt.expiration=86400000

# CORS
cors.allowed-origins=http://localhost:4200,http://petshop-care.cesit.uea.edu.br
